update check wifi password for android 11
mzlogin/awesome-adb pull request #83
Opened 2021-04-25 06:52 UTC by h0wardch3ng

update check wifi password for android 11

2021-04-25 11:02 UTC, mzlogin requested changes
有两个多余的文件，需要删除哈～

2021-04-25 11:02 UTC, mzlogin commented on README.md
> +如果 Android O 密码保存的地址有变化，是在 `WifiConfigStore.xml` 里面
这里不太通顺，可以润色下哈，比如 `如果系统版本是 Android O 或更高的，密码保存地址有变化`。

2021-04-25 11:02 UTC, mzlogin commented on README.md
> +如果 Android 11 或以后，WiFi 密码保存的地址有变化，是在 `WifiConfigStore.xml` 里面
同上

2021-04-26 07:42 UTC, h0wardch3ng commented on README.md
> +如果 Android O 密码保存的地址有变化，是在 `WifiConfigStore.xml` 里面
要不你补充一下吧，另外把我的pr拒绝掉，最近比较忙

2021-05-06 01:26 UTC, mzlogin commented
OK, thx!

2021-05-06 01:26 UTC, closed without merging